// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEDSupY8VIkcVYuQgbmqVSoGwuKZtFIpU',
    appId: '1:712528309288:web:3ecb3a495a424c923b191d',
    messagingSenderId: '712528309288',
    projectId: 'mini-feed-b740d',
    authDomain: 'mini-feed-b740d.firebaseapp.com',
    storageBucket: 'mini-feed-b740d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtmvW0okvbDvSZ7Peb8PnXAuHJ23_-atY',
    appId: '1:712528309288:android:8f6aed5d31b4184a3b191d',
    messagingSenderId: '712528309288',
    projectId: 'mini-feed-b740d',
    storageBucket: 'mini-feed-b740d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATF-2DkZzK12Qk5uy0hhb1sjvf9VnsiE0',
    appId: '1:712528309288:ios:81c3dccc8ba6d6113b191d',
    messagingSenderId: '712528309288',
    projectId: 'mini-feed-b740d',
    storageBucket: 'mini-feed-b740d.firebasestorage.app',
    iosBundleId: 'com.example.miniFeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATF-2DkZzK12Qk5uy0hhb1sjvf9VnsiE0',
    appId: '1:712528309288:ios:e794a1954f5750463b191d',
    messagingSenderId: '712528309288',
    projectId: 'mini-feed-b740d',
    storageBucket: 'mini-feed-b740d.firebasestorage.app',
    iosBundleId: 'com.example.miniFeed.RunnerTests',
  );
}
